apiVersion: v1
kind: Service
metadata:
  name: flask-aws-monitor-service
  labels:
    app: flask-aws-monitor
spec:
  selector:
    app: flask-aws-monitor
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
  type: LoadBalancer